# Scripts to create all prompt sidecars
import os

assets = [
    ("frontend/public/assets/scenes/werewolf-campfire.prompt.md", "Cinematic illustration of a dark forest clearing at night. A crackling campfire in the center, sparks flying into the cold air. Dense pine trees in the background under a pale, full moon. Long shadows cast by the firelight. Atmosphere is ominous, suspenseful, and isolated. 8k resolution, high detail."),
    ("frontend/public/assets/scenes/shanghai-mahjong-alley.prompt.md", "Cinematic illustration of a narrow Shanghai alleyway (Longtang) at dusk. A mahjong table set up outdoors with dim overhead streetlights. Steam rising from nearby food stalls. Retro neon signs in the background. Atmosphere is nostalgic, lively, and filled with local community vibes. 8k resolution, high detail."),
    ("frontend/public/assets/scenes/poker-club-lounge.prompt.md", "Cinematic illustration of a luxury private poker club lounge. A high-quality green velvet table under a warm, low-hanging spotlight. Smoke curling in the air. Plush leather armchairs, dark mahogany walls decorated with abstract art. A glass of whiskey on a side table. Atmosphere is sophisticated, quiet, and high-stakes. 8k resolution, high detail."),
    ("frontend/public/assets/characters/detective-gray.prompt.md", "Cinematic character portrait of a middle-aged male detective named Gray. Wearing a sharp dark trench coat and a fedora. Stern and observant expression, sharp eyes. Holding a vintage leather notebook and a fountain pen. Background is a blurred library or study. High-end digital illustration, rich textures, atmospheric lighting. 8k resolution."),
    ("frontend/public/assets/characters/selina-widow.prompt.md", "Cinematic character portrait of an elegant lady named Selina. Wearing a sophisticated black lace dress and a delicate black veil covering the upper part of her face. Mysterious and melancholic expression. Holding a lace handkerchief. Background is a blurred Victorian parlor with warm candlelight. High-end digital illustration, soft lighting, intricate lace details. 8k resolution."),
    ("frontend/public/assets/characters/seer-white.prompt.md", "Cinematic character portrait of a mystical female seer named White. Wearing a flowing white hooded cloak with silver embroidery. Serene and ethereal expression. Her hands are hovering over a faint, glowing energy sphere. Background is a blurred snowy forest at night. High-end digital illustration, magical lighting, soft glow. 8k resolution."),
    ("frontend/public/assets/characters/samuel-villager.prompt.md", "Cinematic character portrait of a suspicious-looking male villager named Samuel. Wearing simple, worn-out linen clothes and a vest. A weathered face with a hidden, sinister look in his eyes. Holding a wooden lantern. Background is a blurred dark forest edge with campfire reflections. High-end digital illustration, high contrast, dramatic shadows. 8k resolution."),
    ("frontend/public/assets/characters/auntie-zhang.prompt.md", "Cinematic character portrait of a friendly and talkative middle-aged Chinese woman named Auntie Zhang. Wearing a bright red hand-knitted sweater and a modest jade necklace. Permed hair, warm and energetic smile. Background is a blurred busy Shanghai street market with lanterns and retro signs. High-end digital illustration, vibrant colors, warm lighting. 8k resolution."),
    ("frontend/public/assets/characters/dealer-monica.prompt.md", "Cinematic character portrait of a professional female dealer named Monica. Wearing a sleek, dark charcoal business vest over a crisp white shirt. Neutral, calm, and highly professional expression. Holding a deck of high-end playing cards. Background is a blurred luxury lounge with warm, golden accent lights. High-end digital illustration, sharp focus, sophisticated atmosphere. 8k resolution.")
]

for path, prompt in assets:
    content = f"## Final prompt\n{prompt}\n\n## Asset Info\n- **Path**: `{path.replace('.prompt.md', '.png')}`\n- **Style**: Cinematic Illustration\n- **Generated**: 2026-05-11\n"
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
print("All sidecars created.")
